// Copyright (c) 2021-2025 Samsung Electronics Co., Ltd.
// Copyright (c) 2026 Mikhail Kurinnoi
// Distributed under the MIT License.
// See the LICENSE file in the project root for more information.

#include "debugger/breakpoints/breakpoint_break.h"
#include "debugger/threads.h"
#include "debuginfo/debuginfo.h"
#include "utils/hresult.h"
#include "utils/torelease.h"
#include <mutex>

namespace dncdbg::BreakBreakpoint
{

namespace
{

struct FullyQualifiedIlOffset_t
{
    CORDB_ADDRESS modAddress = 0;
    mdMethodDef methodToken = mdMethodDefNil;
    uint32_t ilOffset = 0;

    void Reset()
    {
        modAddress = 0;
        methodToken = 0;
        ilOffset = 0;
    }
};

std::mutex &GetBreakMutex()
{
    static std::mutex breakMutex;
    return breakMutex;
}

FullyQualifiedIlOffset_t &GetLastStoppedIlOffset()
{
    static FullyQualifiedIlOffset_t lastStoppedIlOffset;
    return lastStoppedIlOffset;
}

HRESULT GetFullyQualifiedIlOffset(ICorDebugThread *pThread, FullyQualifiedIlOffset_t &fullyQualifiedIlOffset)
{
    HRESULT Status = S_OK;
    ToRelease<ICorDebugFrame> trFrame;
    IfFailRet(pThread->GetActiveFrame(&trFrame));
    if (trFrame == nullptr)
    {
        return E_FAIL;
    }

    mdMethodDef methodToken = mdMethodDefNil;
    IfFailRet(trFrame->GetFunctionToken(&methodToken));

    ToRelease<ICorDebugFunction> trFunc;
    IfFailRet(trFrame->GetFunction(&trFunc));

    ToRelease<ICorDebugModule> trModule;
    IfFailRet(trFunc->GetModule(&trModule));

    CORDB_ADDRESS modAddress = 0;
    IfFailRet(trModule->GetBaseAddress(&modAddress));

    ToRelease<ICorDebugILFrame> trILFrame;
    IfFailRet(trFrame->QueryInterface(IID_ICorDebugILFrame, reinterpret_cast<void **>(&trILFrame)));

    uint32_t ilOffset = 0;
    CorDebugMappingResult mappingResult = MAPPING_NO_INFO;
    IfFailRet(trILFrame->GetIP(&ilOffset, &mappingResult));
    if (mappingResult == MAPPING_UNMAPPED_ADDRESS ||
        mappingResult == MAPPING_NO_INFO)
    {
        return E_FAIL;
    }

    fullyQualifiedIlOffset.modAddress = modAddress;
    fullyQualifiedIlOffset.methodToken = methodToken;
    fullyQualifiedIlOffset.ilOffset = ilOffset;

    return S_OK;
}

} // unnamed namespace

void SetLastStoppedIlOffset(ICorDebugThread *pThread)
{
    const std::scoped_lock<std::mutex> lock(GetBreakMutex());

    GetLastStoppedIlOffset().Reset();

    if (pThread != nullptr)
    {
        GetFullyQualifiedIlOffset(pThread, GetLastStoppedIlOffset());
    }
}

HRESULT ManagedCallbackBreak(ICorDebugThread *pThread, const ThreadId &lastStoppedThreadId)
{
    HRESULT Status = S_OK;
    ToRelease<ICorDebugFrame> trFrame;
    IfFailRet(pThread->GetActiveFrame(&trFrame));

    // Ignore break on Break() outside of code with loaded PDB (see JMC setup during module load).
    if (trFrame != nullptr)
    {
        ToRelease<ICorDebugFunction> trFunction;
        IfFailRet(trFrame->GetFunction(&trFunction));
        ToRelease<ICorDebugFunction2> trFunction2;
        IfFailRet(trFunction->QueryInterface(IID_ICorDebugFunction2, reinterpret_cast<void **>(&trFunction2)));
        BOOL JMCStatus = FALSE;
        IfFailRet(trFunction2->GetJMCStatus(&JMCStatus));

        if (JMCStatus == FALSE)
        {
            return S_IGNORE;
        }
    }

    const ThreadId threadId(Threads::GetId(pThread));

    // Prevent a duplicate stop event if the previous stop event was for the same thread and the same code point.
    // The idea is to store the "fully-qualified IL offset" (data for module + method + IL) on any stop event
    // and check the real sequence point (required delegate call) only at the Break() callback.
    // Note, the step/breakpoint/etc stop event at the "Debugger.Break()" source line and the stop event
    // generated by CoreCLR during Debugger.Break() execution in managed code have different IL offsets,
    // but the same sequence point.

    const std::scoped_lock<std::mutex> lock(GetBreakMutex());

    const FullyQualifiedIlOffset_t &lastStoppedIlOffset = GetLastStoppedIlOffset();

    if (threadId != lastStoppedThreadId ||
        lastStoppedIlOffset.modAddress == 0 ||
        lastStoppedIlOffset.methodToken == 0)
    {
        return S_OK;
    }

    FullyQualifiedIlOffset_t fullyQualifiedIlOffset;
    IfFailRet(GetFullyQualifiedIlOffset(pThread, fullyQualifiedIlOffset));

    if (fullyQualifiedIlOffset.modAddress != lastStoppedIlOffset.modAddress ||
        fullyQualifiedIlOffset.methodToken != lastStoppedIlOffset.methodToken)
    {
        return S_OK;
    }

    PDB::SequencePoint lastSP;
    IfFailRet(DebugInfo::GetSequencePointByILOffset(lastStoppedIlOffset.modAddress, lastStoppedIlOffset.methodToken,
                                                    lastStoppedIlOffset.ilOffset, lastSP));

    PDB::SequencePoint curSP;
    IfFailRet(DebugInfo::GetSequencePointByILOffset(fullyQualifiedIlOffset.modAddress, fullyQualifiedIlOffset.methodToken,
                                                    fullyQualifiedIlOffset.ilOffset, curSP));

    if (lastSP.startLine != curSP.startLine ||
        lastSP.startColumn != curSP.startColumn ||
        lastSP.endLine != curSP.endLine ||
        lastSP.endColumn != curSP.endColumn ||
        lastSP.ilOffset != curSP.ilOffset ||
        lastSP.sourceFileIndex != curSP.sourceFileIndex)
    {
        return S_OK;
    }

    return S_IGNORE;
}

void Cleanup()
{
    const std::scoped_lock<std::mutex> lock(GetBreakMutex());
    GetLastStoppedIlOffset().Reset();
}

} // namespace dncdbg::BreakBreakpoint
