// Copyright (c) 2021-2025 Samsung Electronics Co., Ltd.
// Copyright (c) 2026 Mikhail Kurinnoi
// Distributed under the MIT License.
// See the LICENSE file in the project root for more information.

#include "debugger/breakpoints/breakpoint_break.h"
#include "debugger/threads.h"
#include "debuginfo/debuginfo.h" // NOLINT(misc-include-cleaner)
#include "utils/torelease.h"

namespace dncdbg
{

HRESULT BreakBreakpoint::GetFullyQualifiedIlOffset(ICorDebugThread *pThread, FullyQualifiedIlOffset_t &fullyQualifiedIlOffset)
{
    HRESULT Status = S_OK;
    ToRelease<ICorDebugFrame> trFrame;
    IfFailRet(pThread->GetActiveFrame(&trFrame));
    if (trFrame == nullptr)
    {
        return E_FAIL;
    }

    mdMethodDef methodToken = mdMethodDefNil;
    IfFailRet(trFrame->GetFunctionToken(&methodToken));

    ToRelease<ICorDebugFunction> trFunc;
    IfFailRet(trFrame->GetFunction(&trFunc));

    ToRelease<ICorDebugModule> trModule;
    IfFailRet(trFunc->GetModule(&trModule));

    CORDB_ADDRESS modAddress = 0;
    IfFailRet(trModule->GetBaseAddress(&modAddress));

    ToRelease<ICorDebugILFrame> trILFrame;
    IfFailRet(trFrame->QueryInterface(IID_ICorDebugILFrame, reinterpret_cast<void **>(&trILFrame)));

    uint32_t ilOffset = 0;
    CorDebugMappingResult mappingResult = MAPPING_NO_INFO;
    IfFailRet(trILFrame->GetIP(&ilOffset, &mappingResult));
    if (mappingResult == MAPPING_UNMAPPED_ADDRESS ||
        mappingResult == MAPPING_NO_INFO)
    {
        return E_FAIL;
    }

    fullyQualifiedIlOffset.modAddress = modAddress;
    fullyQualifiedIlOffset.methodToken = methodToken;
    fullyQualifiedIlOffset.ilOffset = ilOffset;

    return S_OK;
}

void BreakBreakpoint::SetLastStoppedIlOffset(ICorDebugProcess *pProcess, const ThreadId &lastStoppedThreadId)
{
    const std::scoped_lock<std::mutex> lock(m_breakMutex);

    m_lastStoppedIlOffset.Reset();

    if (lastStoppedThreadId == ThreadId::AllThreads)
    {
        return;
    }

    ToRelease<ICorDebugThread> trThread;
    if (SUCCEEDED(pProcess->GetThread(static_cast<int>(lastStoppedThreadId), &trThread)))
    {
        GetFullyQualifiedIlOffset(trThread, m_lastStoppedIlOffset);
    }
}

HRESULT BreakBreakpoint::ManagedCallbackBreak(ICorDebugThread *pThread, const ThreadId &lastStoppedThreadId)
{
    HRESULT Status = S_OK;
    ToRelease<ICorDebugFrame> trFrame;
    IfFailRet(pThread->GetActiveFrame(&trFrame));

    // Ignore break on Break() outside of code with loaded PDB (see JMC setup during module load).
    if (trFrame != nullptr)
    {
        ToRelease<ICorDebugFunction> trFunction;
        IfFailRet(trFrame->GetFunction(&trFunction));
        ToRelease<ICorDebugFunction2> trFunction2;
        IfFailRet(trFunction->QueryInterface(IID_ICorDebugFunction2, reinterpret_cast<void **>(&trFunction2)));
        BOOL JMCStatus = FALSE;
        IfFailRet(trFunction2->GetJMCStatus(&JMCStatus));

        if (JMCStatus == FALSE)
        {
            return S_OK;
        }
    }

    const ThreadId threadId(getThreadId(pThread));

    // Prevent stop event duplicate, if previous stop event was for same thread and same code point.
    // The idea is - store "fully qualified IL offset" (data for module + method + IL) on any stop event
    // and only at Break() callback check the real sequence point (required delegate call).
    // Note, that step/breakpoint/etc stop event at "Debugger.Break()" source line and stop event
    // generated by CoreCLR during Debugger.Break() execution in managed code have different IL offsets,
    // but same sequence point.

    const std::scoped_lock<std::mutex> lock(m_breakMutex);

    if (threadId != lastStoppedThreadId ||
        m_lastStoppedIlOffset.modAddress == 0 ||
        m_lastStoppedIlOffset.methodToken == 0)
    {
        return S_FALSE;
    }

    FullyQualifiedIlOffset_t fullyQualifiedIlOffset;
    IfFailRet(GetFullyQualifiedIlOffset(pThread, fullyQualifiedIlOffset));

    if (fullyQualifiedIlOffset.modAddress != m_lastStoppedIlOffset.modAddress ||
        fullyQualifiedIlOffset.methodToken != m_lastStoppedIlOffset.methodToken)
    {
        return S_FALSE;
    }

    SequencePoint lastSP;
    IfFailRet(m_sharedDebugInfo->GetSequencePointByILOffset(m_lastStoppedIlOffset.modAddress, m_lastStoppedIlOffset.methodToken,
                                                            m_lastStoppedIlOffset.ilOffset, lastSP));

    SequencePoint curSP;
    IfFailRet(m_sharedDebugInfo->GetSequencePointByILOffset(fullyQualifiedIlOffset.modAddress, fullyQualifiedIlOffset.methodToken,
                                                            fullyQualifiedIlOffset.ilOffset, curSP));

    if (lastSP.startLine != curSP.startLine ||
        lastSP.startColumn != curSP.startColumn ||
        lastSP.endLine != curSP.endLine ||
        lastSP.endColumn != curSP.endColumn ||
        lastSP.offset != curSP.offset ||
        lastSP.document != curSP.document)
    {
        return S_FALSE;
    }

    return S_OK;
}

} // namespace dncdbg
