// Copyright (c) 2017-2025 Samsung Electronics Co., Ltd.
// Copyright (c) 2026 Mikhail Kurinnoi
// Distributed under the MIT License.
// See the LICENSE file in the project root for more information.

#include "debugger/frames.h"
#include "debugger/evalhelpers.h"
#include "debuginfo/debuginfo.h"
#include "metadata/modules.h"
#include "metadata/typeprinter.h"
#include "utils/hresult.h"
#include "utils/torelease.h"
#include <algorithm>
#include <iterator>
#include <list>
#include <vector>

namespace dncdbg
{

namespace
{

enum class FrameType : uint8_t
{
    Unknown,
    CLRNative,
    CLRInternal,
    CLRManaged,
    CLRManagedException,
    CLRManagedExceptionUser
};

HRESULT GetActiveInternalFrames(const ToRelease<ICorDebugThread3> &trThread3, std::list<ToRelease<ICorDebugInternalFrame2>> &trInternalFrames)
{
    HRESULT Status = S_OK;
    uint32_t cInternalFrames = 0;
    IfFailRet(trThread3->GetActiveInternalFrames(0, &cInternalFrames, nullptr));

    uint32_t fetchedFrames = 0;
    std::vector<ICorDebugInternalFrame2 *> pInternalFrames(cInternalFrames);
    if (SUCCEEDED(trThread3->GetActiveInternalFrames(cInternalFrames, &fetchedFrames, pInternalFrames.data())) &&
        fetchedFrames == cInternalFrames)
    {
        std::transform(pInternalFrames.begin(), pInternalFrames.end(),
                       std::back_inserter(trInternalFrames), [](ICorDebugInternalFrame2 *p)
                       {
                           return ToRelease<ICorDebugInternalFrame2>(p);
                       });
    }
    else
    {
        return E_FAIL;
    }

    return S_OK;
}

bool AllowInternalFrame(ICorDebugInternalFrame2 *pInternalFrame2, bool lastFrames)
{
    ToRelease<ICorDebugInternalFrame> trInternalFrame;
    CorDebugInternalFrameType corFrameType = STUBFRAME_NONE;
    if (SUCCEEDED(pInternalFrame2->QueryInterface(IID_ICorDebugInternalFrame, reinterpret_cast<void **>(&trInternalFrame))))
    {
        trInternalFrame->GetFrameType(&corFrameType);
    }
    else
    {
        return false;
    }

    if (lastFrames)
    {
        return corFrameType != STUBFRAME_NONE;
    }

    switch (corFrameType)
    {
    case STUBFRAME_APPDOMAIN_TRANSITION:
    case STUBFRAME_LIGHTWEIGHT_FUNCTION:
    case STUBFRAME_FUNC_EVAL:
    case STUBFRAME_INTERNALCALL:
    case STUBFRAME_CLASS_INIT:
    case STUBFRAME_SECURITY:
    case STUBFRAME_JIT_COMPILATION:
        return true;
    case STUBFRAME_EXCEPTION: // no reason to add `[Exception]` frame on the top of stacktrace
    case STUBFRAME_M2U: // hide managed to native transitions in the middle of stacktrace
    case STUBFRAME_U2M: // hide native to managed transitions in the middle of stacktrace
    case STUBFRAME_NONE:
        return false;
    default:
        assert(false);
        return false;
    }
}

HRESULT GetILOffsetFromNativeAddress(ICorDebugModule *pModule, mdMethodDef methodToken, CORDB_ADDRESS nativeAddress, uint32_t &ilOffset)
{
    if (pModule == nullptr)
    {
        return E_INVALIDARG;
    }

    HRESULT Status = S_OK;
    ToRelease<ICorDebugFunction> trFunction;
    IfFailRet(pModule->GetFunctionFromToken(methodToken, &trFunction));
    ToRelease<ICorDebugCode> trNativeCode;
    IfFailRet(trFunction->GetNativeCode(&trNativeCode));
    CORDB_ADDRESS nativeBaseAddress = 0;
    IfFailRet(trNativeCode->GetAddress(&nativeBaseAddress));
    if (nativeAddress < nativeBaseAddress)
    {
        return E_FAIL; // The address belongs to a different memory region
    }
    auto nativeOffset = static_cast<ULONG32>(nativeAddress - nativeBaseAddress);

    ULONG32 mapElementsCount = 0;
    IfFailRet(trNativeCode->GetILToNativeMapping(0, &mapElementsCount, nullptr));
    if (mapElementsCount == 0)
    {
        return E_FAIL; // Mapping data is unavailable (e.g., lightweight/dynamic methods)
    }

    std::vector<COR_DEBUG_IL_TO_NATIVE_MAP> mapping(mapElementsCount);
    IfFailRet(trNativeCode->GetILToNativeMapping(mapElementsCount, &mapElementsCount, mapping.data()));

    // Search the JIT map to find which IL offset corresponds to our native offset
    ilOffset = 0;

    for (ULONG32 i = 0; i < mapElementsCount; ++i)
    {
        const auto &entry = mapping.at(i);

        // Skip internal CLR runtime markers that do not map to real IL code:
        // - NO_MAPPING (0xffffffff): Code generated by CLR (GC checks, security blocks)
        // - PROLOG     (0xfffffffe): Method initialization code
        // - EPILOG     (0xfffffffd): Method return/cleanup code
        if (entry.ilOffset == static_cast<uint32_t>(NO_MAPPING) ||
            entry.ilOffset == static_cast<uint32_t>(PROLOG) ||
            entry.ilOffset == static_cast<uint32_t>(EPILOG))
        {
            continue;
        }

        // Exact match: The native address points precisely to the start of an instruction boundary
        if (entry.nativeStartOffset == nativeOffset)
        {
            ilOffset = entry.ilOffset;
            break;
        }

        // Closest match: The native address most likely points inside an assembly instruction sequence.
        // We keep track of the closest preceding boundary (the 'left' bound of the instruction sequence).
        if (entry.nativeStartOffset <= nativeOffset)
        {
            ilOffset = entry.ilOffset;
        }
    }

    return S_OK;
}

const char *GetInternalTypeName(CorDebugInternalFrameType frameType)
{
    switch (frameType)
    {
    case STUBFRAME_M2U:
        return "Managed to Native Transition";
    case STUBFRAME_U2M:
        return "Native to Managed Transition";
    case STUBFRAME_APPDOMAIN_TRANSITION:
        return "Appdomain Transition";
    case STUBFRAME_LIGHTWEIGHT_FUNCTION:
        return "Lightweight function";
    case STUBFRAME_FUNC_EVAL:
        return "Func Eval";
    case STUBFRAME_INTERNALCALL:
        return "Internal Call";
    case STUBFRAME_CLASS_INIT:
        return "Class Init";
    case STUBFRAME_EXCEPTION:
        return "Exception";
    case STUBFRAME_SECURITY:
        return "Security";
    case STUBFRAME_JIT_COMPILATION:
        return "JIT Compilation";
    case STUBFRAME_NONE:
        return "Unknown";
    default:
        assert(false);
        return "Unknown";
    }
}

HRESULT GetFrameLocation(ICorDebugFrame *pFrame, ThreadId threadId, FrameLevel level,
                         DebugInfo *pDebugInfo, StackFrame &stackFrame)
{
    HRESULT Status = S_OK;

    std::string methodName;
    if (FAILED(TypePrinter::GetFullyQualifiedMethodName(pFrame, pDebugInfo, methodName)))
    {
        methodName = "[Unnamed managed method in optimized code]";
    }
    stackFrame = StackFrame(threadId, level, methodName);

    ToRelease<ICorDebugFunction> trFunc;
    IfFailRet(pFrame->GetFunction(&trFunc));

    ToRelease<ICorDebugModule> trModule;
    IfFailRet(trFunc->GetModule(&trModule));

    PDB::SequencePoint sp;
    PDB::GlobalFileIndex globalFileIndex;
    if (SUCCEEDED(pDebugInfo->GetSequencePointByFrame(pFrame, sp, &globalFileIndex)))
    {
        std::string sourceFilePath;
        pDebugInfo->GetSourceFile(globalFileIndex, sourceFilePath);

        stackFrame.source = Source(sourceFilePath);
        stackFrame.line = sp.startLine;
        stackFrame.column = sp.startColumn;
        stackFrame.endLine = sp.endLine;
        stackFrame.endColumn = sp.endColumn;
    }

    IfFailRet(Modules::GetModuleMvid(trModule, stackFrame.moduleId));

    return S_OK;
}

using WalkFramesCallback = std::function<HRESULT(FrameType, ICorDebugFrame *, const PDB::SequencePoint *,
                                                 const std::string *, const std::string *)>;

HRESULT WalkFrames(ICorDebugThread *pThread, DebugInfo *pDebugInfo, const WalkFramesCallback &cb)
{
    HRESULT Status = S_OK;

    auto exceptionStackTrace = [&]() -> HRESULT
    {
        ToRelease<ICorDebugThread4> trThread4;
        IfFailRet(pThread->QueryInterface(IID_ICorDebugThread4, reinterpret_cast<void **>(&trThread4)));
        // From third_party/diagnostics/src/shared/inc/cordebug.idl
        // Returns S_OK if ICorDebugThread::GetCurrentException() is non-NULL and the exception
        // it refers to has completed the first pass of exception handling without locating
        // a catch clause.
        // Returns S_FALSE if there is no exception, it hasn't completed the first pass handling,
        // or a catch handler was located.
        IfFailRet(trThread4->HasUnhandledException());
        if (Status == S_FALSE)
        {
            return S_OK;
        }

        ToRelease<ICorDebugValue> trExceptionValueRef;
        IfFailRet(pThread->GetCurrentException(&trExceptionValueRef));
        if (trExceptionValueRef == nullptr)
        {
            return E_FAIL;
        }

        ToRelease<ICorDebugValue> trExceptionValue;
        IfFailRet(DereferenceAndUnboxValue(trExceptionValueRef, &trExceptionValue));
        ToRelease<ICorDebugExceptionObjectValue> trExceptionObjectValue;
        IfFailRet(trExceptionValue->QueryInterface(IID_ICorDebugExceptionObjectValue, reinterpret_cast<void **>(&trExceptionObjectValue)));
        ToRelease<ICorDebugExceptionObjectCallStackEnum> trExceptionObjectCallStackEnum;
        IfFailRet(trExceptionObjectValue->EnumerateExceptionCallStack(&trExceptionObjectCallStackEnum));

        int lastForeignExceptionFrameIndex = -1;
        int index = -1;
        CorDebugExceptionObjectStackFrame exceptionObjectStackFrame;
        ULONG fetched = 0;
        while (SUCCEEDED(trExceptionObjectCallStackEnum->Next(1, &exceptionObjectStackFrame, &fetched)) && fetched == 1)
        {
            exceptionObjectStackFrame.pModule->Release();

            index++;
            if (exceptionObjectStackFrame.isLastForeignExceptionFrame == TRUE)
            {
                lastForeignExceptionFrameIndex = index;
            }
        }
        // Release the first enumerator before reusing the variable for a fresh enumeration.
        trExceptionObjectCallStackEnum.Free();

        // The exception thread was not changed (exception was not rethrown), normal unwind will work without issues.
        if (lastForeignExceptionFrameIndex == -1)
        {
            return S_OK;
        }

        IfFailRet(trExceptionObjectValue->EnumerateExceptionCallStack(&trExceptionObjectCallStackEnum));

        index = -1;
        while (SUCCEEDED(trExceptionObjectCallStackEnum->Next(1, &exceptionObjectStackFrame, &fetched)) && fetched == 1)
        {
            ToRelease<ICorDebugModule> trModule(exceptionObjectStackFrame.pModule);

            index++;
            // Don't unwind stack frames that belong to current thread, normal unwind will do this.
            if (lastForeignExceptionFrameIndex < index)
            {
                break;
            }

            CORDB_ADDRESS modAddress = 0;
            uint32_t ilOffset = 0;
            PDB::SequencePoint sequencePoint;
            std::string sourceFilePath;
            if (FAILED(trModule->GetBaseAddress(&modAddress)) ||
                FAILED(GetILOffsetFromNativeAddress(trModule, exceptionObjectStackFrame.methodDef, exceptionObjectStackFrame.ip, ilOffset)))
            {
                continue;
            }

            std::string methodName;
            if (FAILED(TypePrinter::GetFullyQualifiedMethodName(trModule, exceptionObjectStackFrame.methodDef, pDebugInfo, methodName)))
            {
                methodName = "[Unnamed managed method in optimized code]";
            }

            if (SUCCEEDED(pDebugInfo->GetSequencePointByILOffset(modAddress, exceptionObjectStackFrame.methodDef, ilOffset, sequencePoint)) &&
                SUCCEEDED(pDebugInfo->GetSourceFile({modAddress, sequencePoint.sourceFileIndex}, sourceFilePath)))
            {
                if (cb(FrameType::CLRManagedExceptionUser, nullptr, &sequencePoint, &methodName, &sourceFilePath) == S_CAN_EXIT)
                {
                    return S_CAN_EXIT;
                }
            }
            // Make sure that the last foreign exception frame itself is added to the stack trace.
            else if (exceptionObjectStackFrame.isLastForeignExceptionFrame == TRUE)
            {
                if (cb(FrameType::CLRManagedException, nullptr, nullptr, &methodName, nullptr) == S_CAN_EXIT)
                {
                    return S_CAN_EXIT;
                }
            }
        }

        return S_OK;
    };
    // Exception stack trace first, since foreign exception frames must be upper frames of the stack trace.
    if (exceptionStackTrace() == S_CAN_EXIT)
    {
        return S_OK;
    }

    ToRelease<ICorDebugThread3> trThread3;
    IfFailRet(pThread->QueryInterface(IID_ICorDebugThread3, reinterpret_cast<void **>(&trThread3)));
    ToRelease<ICorDebugStackWalk> trStackWalk;
    IfFailRet(trThread3->CreateStackWalk(&trStackWalk));

    std::list<ToRelease<ICorDebugInternalFrame2>> trInternalFrames;
    GetActiveInternalFrames(trThread3, trInternalFrames);

    for (Status = S_OK; ; Status = trStackWalk->Next())
    {
        if (Status == CORDBG_S_AT_END_OF_STACK ||
            FAILED(Status))
        {
            break;
        }

        ToRelease<ICorDebugFrame> trFrame;
        if (FAILED(Status = trStackWalk->GetFrame(&trFrame)))
        {
            continue;
        }

        if (Status == S_FALSE) // S_FALSE - The current frame is a native stack frame.
        {
            continue;
        }

        // At this point (Status == S_OK).
        // According to CoreCLR sources, S_OK can be returned with a null trFrame, which must be skipped.
        // Related to `FrameType::kExplicitFrame` in runtime (represents a skipped frame function with no frame transition).
        if (trFrame == nullptr)
        {
            continue;
        }

        if (!trInternalFrames.empty())
        {
            BOOL isCloser = TRUE;
            for (auto it = trInternalFrames.begin(); it != trInternalFrames.end(); )
            {
                if (SUCCEEDED((*it)->IsCloserToLeaf(trFrame, &isCloser)) &&
                    isCloser == TRUE)
                {
                    ToRelease<ICorDebugFrame> trIntFrame;
                    if (SUCCEEDED((*it)->QueryInterface(IID_ICorDebugInternalFrame, reinterpret_cast<void **>(&trIntFrame))) &&
                        AllowInternalFrame(*it, false))
                    {
                        if (cb(FrameType::CLRInternal, trIntFrame, nullptr, nullptr, nullptr) == S_CAN_EXIT)
                        {
                            return S_OK;
                        }
                    }
                    it = trInternalFrames.erase(it);
                }
                else
                {
                    ++it;
                }
            }
        }

        // If we get a RuntimeUnwindableFrame, then the stackwalker is also stopped at a native
        // stack frame, but it's a native stack frame which requires special unwinding help from
        // the runtime. When a debugger gets a RuntimeUnwindableFrame, it should use the runtime
        // to unwind, but it has to do inspection on its own. It can call
        // ICorDebugStackWalk::GetContext() to retrieve the context of the native stack frame.
        ToRelease<ICorDebugRuntimeUnwindableFrame> trRuntimeUnwindableFrame;
        if (SUCCEEDED(trFrame->QueryInterface(IID_ICorDebugRuntimeUnwindableFrame, reinterpret_cast<void **>(&trRuntimeUnwindableFrame))))
        {
            continue;
        }

        ToRelease<ICorDebugILFrame> trILFrame;
        if (SUCCEEDED(trFrame->QueryInterface(IID_ICorDebugILFrame, reinterpret_cast<void **>(&trILFrame))))
        {
            uint32_t tmpOffset = 0;
            CorDebugMappingResult mappingResult = MAPPING_NO_INFO;
            if (SUCCEEDED(trILFrame->GetIP(&tmpOffset, &mappingResult)) &&
                (mappingResult == MAPPING_UNMAPPED_ADDRESS ||
                 mappingResult == MAPPING_NO_INFO))
            {
                // Related to ICorDebugInternalFrame, ignore.
                continue;
            }

            // Hide state machine related frames for both JMC and non-JMC cases.
            std::string methodName;
            ToRelease<ICorDebugFunction> trFunction;
            if ((pDebugInfo != nullptr && SUCCEEDED(trFrame->GetFunction(&trFunction)) && pDebugInfo->IsStateMachineKickoffMethod(trFunction)) ||
                (pDebugInfo != nullptr && SUCCEEDED(TypePrinter::GetFullyQualifiedMethodName(trFrame, pDebugInfo, methodName)) &&
                 // Note: starts_with() is C++20, use rfind() for compatibility
                 (methodName.rfind("System.Runtime.CompilerServices.AsyncMethodBuilderCore", 0) == 0 ||
                  methodName.rfind("System.Runtime.CompilerServices.AsyncTaskMethodBuilder", 0) == 0)))
            {
                continue;
            }

            if (cb(FrameType::CLRManaged, trFrame, nullptr, nullptr, nullptr) == S_CAN_EXIT)
            {
                return S_OK;
            }

            continue;
        }

        ToRelease<ICorDebugNativeFrame> trNativeFrame;
        if (SUCCEEDED(trFrame->QueryInterface(IID_ICorDebugNativeFrame, reinterpret_cast<void **>(&trNativeFrame))))
        {
            if (cb(FrameType::CLRNative, nullptr, nullptr, nullptr, nullptr) == S_CAN_EXIT)
            {
                return S_OK;
            }

            continue;
        }

        if (cb(FrameType::Unknown, nullptr, nullptr, nullptr, nullptr) == S_CAN_EXIT)
        {
            return S_OK;
        }
    }

    for (const auto &trIntFrame2 : trInternalFrames)
    {
        ToRelease<ICorDebugFrame> trIntFrame;
        if (SUCCEEDED(trIntFrame2->QueryInterface(IID_ICorDebugInternalFrame, reinterpret_cast<void **>(&trIntFrame))) &&
            AllowInternalFrame(trIntFrame2, true))
        {
            if (cb(FrameType::CLRInternal, trIntFrame, nullptr, nullptr, nullptr) == S_CAN_EXIT)
            {
                return S_OK;
            }
        }
    }

    return S_OK;
}

} // unnamed namespace

HRESULT GetFrameAt(ICorDebugThread *pThread, FrameLevel level, DebugInfo *pDebugInfo, bool justMyCode, ICorDebugFrame **ppFrame)
{
    auto foreignExceptionFrameDetected = [&]() -> bool
    {
        HRESULT Status = S_OK;
        ToRelease<ICorDebugThread4> trThread4;
        if (FAILED(pThread->QueryInterface(IID_ICorDebugThread4, reinterpret_cast<void **>(&trThread4))) ||
            FAILED(Status = trThread4->HasUnhandledException()) ||
            Status == S_FALSE)
        {
            return false;
        }

        ToRelease<ICorDebugValue> trExceptionValueRef;
        if (FAILED(pThread->GetCurrentException(&trExceptionValueRef)) ||
            trExceptionValueRef == nullptr)
        {
            return false;
        }

        ToRelease<ICorDebugValue> trExceptionValue;
        ToRelease<ICorDebugExceptionObjectValue> trExceptionObjectValue;
        if (FAILED(DereferenceAndUnboxValue(trExceptionValueRef, &trExceptionValue)) ||
            FAILED(trExceptionValue->QueryInterface(IID_ICorDebugExceptionObjectValue, reinterpret_cast<void **>(&trExceptionObjectValue))))
        {
            return false;
        }

        CorDebugExceptionObjectStackFrame exceptionObjectStackFrame;
        ULONG fetched = 0;
        ToRelease<ICorDebugExceptionObjectCallStackEnum> trExceptionObjectCallStackEnum;
        if (FAILED(trExceptionObjectValue->EnumerateExceptionCallStack(&trExceptionObjectCallStackEnum)))
        {
            return false;
        }

        while (SUCCEEDED(trExceptionObjectCallStackEnum->Next(1, &exceptionObjectStackFrame, &fetched)) && fetched == 1)
        {
            exceptionObjectStackFrame.pModule->Release();

            if (exceptionObjectStackFrame.isLastForeignExceptionFrame == TRUE)
            {
                return true;
            }
        }

        return false;
    };

    // Try to get 0 (current active) frame in an efficient way, if possible.
    // Note: This optimization is only valid when JMC is disabled, because when JMC is enabled,
    // the active frame might be external code (non-user code) and should not be returned directly.
    if (!justMyCode && static_cast<int>(level) == 0 && !foreignExceptionFrameDetected() &&
        SUCCEEDED(pThread->GetActiveFrame(ppFrame)) && *ppFrame != nullptr)
    {
        return S_OK;
    }

    struct IntWalkFrame
    {
        FrameType frameType;
        ToRelease<ICorDebugFrame> trFrame;

        IntWalkFrame(FrameType frameType_, ICorDebugFrame *pFrame_)
            : frameType(frameType_),
              trFrame(pFrame_)
        {
        }
    };

    std::list<IntWalkFrame> walkFrames;
    static constexpr size_t stackTraceLimit = 250;

    // Store all ICorDebugStackWalk frames output before calling ICorDebug API, since it could corrupt internal states.
    // For example, on macOS arm64 since .NET 9.0, ICorDebugFunction2::GetJMCStatus call breaks ICorDebugStackWalk.
    WalkFrames(pThread, pDebugInfo,
        [&](FrameType frameType, ICorDebugFrame *pFrame, const PDB::SequencePoint *, const std::string *, const std::string *) -> HRESULT
        {
            if (pFrame != nullptr)
            {
                pFrame->AddRef();
            }
            walkFrames.emplace_back(frameType, pFrame);

            if (walkFrames.size() >= stackTraceLimit ||
                (!justMyCode && static_cast<int>(walkFrames.size()) > static_cast<int>(level)))
            {
                return S_CAN_EXIT; // Fast exit from loop.
            }

            return S_OK; // Continue walk.
        });

    int currentFrame = -1;
    bool prevFrameExternal = false;

    for (auto &frame : walkFrames)
    {
        if (justMyCode && frame.frameType != FrameType::CLRManagedExceptionUser)
        {
            ToRelease<ICorDebugFunction> trFunction;
            ToRelease<ICorDebugFunction2> trFunction2;
            BOOL JMCStatus = FALSE;
            if (frame.frameType == FrameType::CLRManaged &&
                SUCCEEDED(frame.trFrame->GetFunction(&trFunction)) &&
                SUCCEEDED(trFunction->QueryInterface(IID_ICorDebugFunction2, reinterpret_cast<void **>(&trFunction2))) &&
                SUCCEEDED(trFunction2->GetJMCStatus(&JMCStatus)) &&
                JMCStatus == TRUE)
            {
                prevFrameExternal = false;
            }
            else
            {
                if (!prevFrameExternal)
                {
                    currentFrame++;
                    prevFrameExternal = true;
                }
                continue;
            }
        }

        currentFrame++;

        if (currentFrame < static_cast<int>(level))
        {
            continue;
        }
        else if (currentFrame > static_cast<int>(level) ||
                 frame.frameType != FrameType::CLRManaged)
        {
            break;
        }

        *ppFrame = frame.trFrame.Detach();
        break;
    }

    return *ppFrame != nullptr ? S_OK : E_FAIL;
}

HRESULT GetStackFrames(ICorDebugThread *pThread, ThreadId threadId, FrameLevel startFrame, unsigned maxFrames,
                       DebugInfo *pDebugInfo, bool justMyCode, std::vector<StackFrame> &stackFrames)
{
    // CoreCLR native frame, could be part of transition to at least one user's native frame.
    static const std::string FrameCLRNativeText = "[CLR Native Frame]";
    // This frame usually indicates some fail during managed unwind.
    static const std::string FrameUnknownText = "[Unknown Frame]";
    // Non-user code related frame when Just My Code is enabled.
    static const std::string ExternalCodeText = "[External Code]";
    // Prefix for foreign exception stack frames (frames from a rethrown exception's original thread).
    static const std::string ExceptionFramePrefix = "[Exception] ";
    // Mark that stack trace was truncated.
    static const std::string TruncatedStackTrace = "[Truncated Stack Trace]";

    struct IntWalkExceptionFrame
    {
        PDB::SequencePoint sequencePoint;
        std::string methodName;
        std::string sourceFilePath;
        IntWalkExceptionFrame(const PDB::SequencePoint *sequencePoint_, const std::string *methodName_, const std::string *sourceFilePath_)
            : sequencePoint(sequencePoint_ != nullptr ? *sequencePoint_ : PDB::SequencePoint{}),
              methodName(methodName_ != nullptr ? *methodName_ : ""),
              sourceFilePath(sourceFilePath_ != nullptr ? *sourceFilePath_ : "")
        {
        }
    };

    struct IntWalkFrame
    {
        FrameType frameType;
        ToRelease<ICorDebugFrame> trFrame;
        IntWalkExceptionFrame *excFrame{nullptr};

        IntWalkFrame(FrameType frameType_, ICorDebugFrame *pFrame_)
            : frameType(frameType_),
              trFrame(pFrame_)
        {
        }
    };

    std::list<IntWalkFrame> walkFrames;
    std::list<IntWalkExceptionFrame> walkExceptionFrames;
    static constexpr size_t stackTraceLimit = 250;
    bool stackTruncated = false;

    // Store all ICorDebugStackWalk frames output before calling ICorDebug API, since it could corrupt internal states.
    // For example, on macOS arm64 since .NET 9.0, ICorDebugFunction2::GetJMCStatus call breaks ICorDebugStackWalk.
    WalkFrames(pThread, pDebugInfo,
        [&](FrameType frameType, ICorDebugFrame *pFrame, const PDB::SequencePoint *sequencePoint,
            const std::string *methodName, const std::string *sourceFilePath) -> HRESULT
        {
            if (pFrame != nullptr)
            {
                pFrame->AddRef();
            }

            if (walkFrames.size() >= stackTraceLimit)
            {
                stackTruncated = true;
                return S_CAN_EXIT; // Fast exit from loop.
            }

            walkFrames.emplace_back(frameType, pFrame);

            if (frameType == FrameType::CLRManagedException ||
                frameType == FrameType::CLRManagedExceptionUser)
            {
                walkExceptionFrames.emplace_back(sequencePoint, methodName, sourceFilePath);
                walkFrames.back().excFrame = &walkExceptionFrames.back();
            }

            if (!justMyCode && maxFrames != 0 &&
                static_cast<int>(walkFrames.size()) >= static_cast<int>(startFrame) + static_cast<int>(maxFrames))
            {
                return S_CAN_EXIT; // Fast exit from loop.
            }

            return S_OK; // Continue walk.
        });

    int currentFrame = -1;
    bool prevFrameExternal = false;

    for (auto &frame : walkFrames)
    {
        if (justMyCode && frame.frameType != FrameType::CLRManagedExceptionUser)
        {
            ToRelease<ICorDebugFunction> trFunction;
            ToRelease<ICorDebugFunction2> trFunction2;
            BOOL JMCStatus = FALSE;
            if (frame.frameType == FrameType::CLRManaged &&
                SUCCEEDED(frame.trFrame->GetFunction(&trFunction)) &&
                SUCCEEDED(trFunction->QueryInterface(IID_ICorDebugFunction2, reinterpret_cast<void **>(&trFunction2))) &&
                SUCCEEDED(trFunction2->GetJMCStatus(&JMCStatus)) &&
                JMCStatus == TRUE)
            {
                prevFrameExternal = false;
            }
            else
            {
                if (!prevFrameExternal)
                {
                    currentFrame++;
                    stackFrames.emplace_back(threadId, FrameLevel{currentFrame}, ExternalCodeText);
                    prevFrameExternal = true;
                }
                continue;
            }
        }

        currentFrame++;

        if (currentFrame < static_cast<int>(startFrame))
        {
            continue;
        }
        if (maxFrames != 0 && currentFrame >= static_cast<int>(startFrame) + static_cast<int>(maxFrames))
        {
            break;
        }

        switch (frame.frameType)
        {
        case FrameType::Unknown:
            stackFrames.emplace_back(threadId, FrameLevel{currentFrame}, FrameUnknownText);
            break;
        case FrameType::CLRNative:
            stackFrames.emplace_back(threadId, FrameLevel{currentFrame}, FrameCLRNativeText);
            break;
        case FrameType::CLRInternal:
        {
            ToRelease<ICorDebugInternalFrame> trInternalFrame;
            CorDebugInternalFrameType corFrameType = STUBFRAME_NONE;
            if (SUCCEEDED(frame.trFrame->QueryInterface(IID_ICorDebugInternalFrame, reinterpret_cast<void **>(&trInternalFrame))))
            {
                trInternalFrame->GetFrameType(&corFrameType);
            }
            std::string name = "[";
            name += GetInternalTypeName(corFrameType);
            name += "]";
            stackFrames.emplace_back(threadId, FrameLevel{currentFrame}, name);
            break;
        }
        case FrameType::CLRManaged:
        {
            StackFrame stackFrame;
            GetFrameLocation(frame.trFrame, threadId, FrameLevel{currentFrame}, pDebugInfo, stackFrame);
            stackFrames.push_back(stackFrame);
            break;
        }
        case FrameType::CLRManagedException:
        case FrameType::CLRManagedExceptionUser:
        {
            stackFrames.emplace_back(threadId, FrameLevel{currentFrame}, ExceptionFramePrefix + frame.excFrame->methodName);
            if (frame.frameType == FrameType::CLRManagedExceptionUser)
            {
                stackFrames.back().source = Source(frame.excFrame->sourceFilePath);
                stackFrames.back().line = frame.excFrame->sequencePoint.startLine;
                stackFrames.back().endLine = frame.excFrame->sequencePoint.endLine;
            }
            break;
        }
        }
    }

    if (stackTruncated)
    {
        stackFrames.emplace_back(threadId, FrameLevel{currentFrame}, TruncatedStackTrace);
    }

    return S_OK;
}

} // namespace dncdbg
