# Build-time generator for buildinfo_vcs.h (DNCDBG_VCS_INFO for src/buildinfo.cpp),
# run as `cmake -P` by the `buildinfo` target on every build. Inputs: SRC_DIR, OUTPUT_FILE.

# Extract current revision from .git (only .git/HEAD referenced); optional
# argument: source tree root. The result might be an empty string on error.
function(VCSInfo result)
    if (${ARGC} GREATER 1)
        set(path "${ARGV1}")
    else()
        get_filename_component(path . REALPATH)
    endif()
    set(git_dir "${path}/.git")

    set(revision "")
    if (IS_DIRECTORY "${git_dir}")
        file(READ "${git_dir}/HEAD" git_head)
        if (git_head MATCHES "^ref:")
            string(REGEX REPLACE "^ref:[ \t]*([^ \t\r\n]+).*" "\\1" git_ref "${git_head}")
            if (EXISTS "${git_dir}/${git_ref}")
                file(READ "${git_dir}/${git_ref}" revision)
                string(REGEX MATCH "^......." revision "${revision}")
            else()
                set(revision ${git_ref})
            endif()
        else()
            set(revision ${git_head})
            string(REGEX MATCH "^......." revision "${revision}")
        endif()

    elseif((NOT path STREQUAL "/") AND (NOT ${path} MATCHES ".*:/$"))
        get_filename_component(parent_dir "${path}" PATH)
        VCSInfo(revision ${parent_dir})
    endif()

    if (revision STREQUAL "")
        set(${result} "\"not detected\"" PARENT_SCOPE)
    else()
        set(${result} "${revision}" PARENT_SCOPE)
    endif()
endfunction(VCSInfo)

VCSInfo(dncdbg_vcs_info "${SRC_DIR}")

file(WRITE "${OUTPUT_FILE}" "// Generated by cmake/buildinfovcs.cmake - do not edit.
// Contains the VCS revision of the current source tree snapshot.
#ifndef BUILDINFO_VCS_H
#define BUILDINFO_VCS_H

#define DNCDBG_VCS_INFO ${dncdbg_vcs_info} // NOLINT(cppcoreguidelines-macro-usage)

#endif // BUILDINFO_VCS_H
")
